name: CI/CD Pipeline

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build frontend
      working-directory: ./frontend
      run: |
        npm install
        npm run build

    - name: Build backend
      working-directory: ./backend
      run: |
        npm install

    - name: Build Docker images
      run: |
        docker build -t devilvires/inter-frontend-app:01 ./frontend
        docker build -t devilvires/inter-backend-app:01 ./backend

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker images
      run: |
        docker tag inter-frontend-app devilvires/inter-frontend-app:01
        docker tag inter-backend-app devilvires/inter-backend-app:01
        docker push devilvires/inter-frontend-app:01
        docker push devilvires/inter-backend-app:01

    # - name: Deploy to AWS
#   uses: aws-actions/configure-aws-credentials@v1
#   with:
#     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#     aws-region: us-east-1

# - name: Deploy to ECS
#   run: |
# # Install kubectl
# curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl
# chmod +x ./kubectl
# sudo mv ./kubectl /usr/local/bin/

# # Update kubeconfig
# aws eks update-kubeconfig --region us-east-1 --name your-cluster-name

# # Deploy Kubernetes resources
# kubectl apply -f k8s/
